name: Update YouTube Music Stats on Profile

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Faz o checkout do REPOSITÓRIO DO PERFIL para uma pasta chamada 'profile'
      - name: Checkout profile repository
        uses: actions/checkout@v4
        with:
          repository: pajeeh/pajeeh # IMPORTANTE: Verifique se este é o nome correto
          token: ${{ secrets.GH_PAT }} # Usa o PAT para ter permissão de escrita
          path: 'profile' # Clona para uma pasta específica

      # Passo 2: Faz o checkout deste repositório (dynamic-youtube-readme)
      - name: Checkout action repository
        uses: actions/checkout@v4
        
      # Passo 3: Configura o Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Passo 4: Instala as dependências
      - name: Instalar dependências
        run: pip install -r requirements.txt

      # Passo 5: Cria o arquivo de autenticação a partir do Secret
      - name: Criar arquivo de autenticação
        run: echo "${{ secrets.YT_MUSIC_OAUTH_JSON }}" > oauth.json
      
      # Passo 6: Roda o script Python, passando o caminho do README do perfil
      - name: Run Python script to update profile README
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
        run: python update_readme.py ./pajeeh/README.md

      # Passo 7: Faz o commit e push DAS MUDANÇAS NO REPOSITÓRIO DO PERFIL
      - name: Commit and push changes
        run: |
          cd profile
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "🎵 Update YouTube Music stats" && git push)